-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           5.5.8 - MySQL Community Server (GPL)
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Copiando estrutura do banco de dados para showdomilhao
CREATE DATABASE IF NOT EXISTS `showdomilhao` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `showdomilhao`;

-- Copiando estrutura para tabela showdomilhao.alternativas
CREATE TABLE IF NOT EXISTS `alternativas` (
  `ID_Alternativa` int(11) NOT NULL AUTO_INCREMENT,
  `Letra` varchar(1) DEFAULT NULL,
  `Conteudo` varchar(300) DEFAULT NULL,
  `Alternativa_correta` char(3) DEFAULT NULL,
  KEY `ID_Alternativa` (`ID_Alternativa`),
  CONSTRAINT `alternativas_ibfk_1` FOREIGN KEY (`ID_Alternativa`) REFERENCES `perguntas` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=301 DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela showdomilhao.alternativas: ~1.374 rows (aproximadamente)
/*!40000 ALTER TABLE `alternativas` DISABLE KEYS */;
INSERT INTO `alternativas` (`ID_Alternativa`, `Letra`, `Conteudo`, `Alternativa_correta`) VALUES
	(1, 'A', 'Rio De Janeiro', 'Nao'),
	(1, 'B', 'Rio Grande Do Sul', 'Sim'),
	(1, 'C', 'Santa Catarina', 'Nao'),
	(1, 'D', 'Goiás', 'Nao'),
	(2, 'A', 'Líquido', 'Nao'),
	(2, 'B', 'Sólido', 'Sim'),
	(2, 'C', 'Gasoso', 'Nao'),
	(2, 'D', 'Vaporoso', 'Nao'),
	(3, 'A', 'Gauchinha', 'Nao'),
	(3, 'B', 'Paulistinha', 'Nao'),
	(3, 'C', 'Pimentinha', 'Sim'),
	(3, 'D', 'Andorinha', 'Nao'),
	(4, 'A', 'Margarida', 'Nao'),
	(4, 'B', 'Minnie', 'Sim'),
	(4, 'C', 'A Pequena Sereia', 'Nao'),
	(4, 'D', 'Olívia Palito', 'Nao'),
	(5, 'A', 'Cuca', 'Nao'),
	(5, 'B', 'Negrinho do Pastoreio', 'Nao'),
	(5, 'C', 'Boitatá', 'Nao'),
	(5, 'D', 'Saci-Pererê', 'Sim'),
	(6, 'A', 'Jamaica', 'Nao'),
	(6, 'B', 'Cuba', 'Sim'),
	(6, 'C', 'El Salvador', 'Nao'),
	(6, 'D', 'México', 'Nao'),
	(7, 'A', 'Duque de Caxias', 'Nao'),
	(7, 'B', 'Marechal Rondon', 'Nao'),
	(7, 'C', 'Dom Pedro II', 'Nao'),
	(7, 'D', 'Marechal Deodoro', 'Sim'),
	(8, 'A', 'Marechal Deodoro', 'Nao'),
	(8, 'B', 'Barão de Maliá', 'Nao'),
	(8, 'C', 'Duque de Caxias', 'Sim'),
	(8, 'D', 'Marquês de Pombal', 'Nao'),
	(9, 'A', 'Raul Gil', 'Nao'),
	(9, 'B', 'Bolinha', 'Nao'),
	(9, 'C', 'Flávio Cavalcanti', 'Nao'),
	(9, 'D', 'Chacrinha', 'Sim'),
	(10, 'A', 'Monstro', 'Sim'),
	(10, 'B', 'Gorila', 'Nao'),
	(10, 'C', 'Príncipe', 'Nao'),
	(10, 'D', 'Sapo', 'Nao'),
	(11, 'A', 'Virgem', 'Nao'),
	(11, 'B', 'Aquário', 'Nao'),
	(11, 'C', 'Capricórnio', 'Sim'),
	(11, 'D', 'Áries', 'Nao'),
	(12, 'A', 'Harrison Ford', 'Nao'),
	(12, 'B', 'Gerald Ford', 'Nao'),
	(12, 'C', 'Henry Ford', 'Sim'),
	(12, 'D', 'Anna Ford', 'Nao'),
	(13, 'A', 'Preta', 'Nao'),
	(13, 'B', 'Vermelha', 'Nao'),
	(13, 'C', 'Azul', 'Nao'),
	(13, 'D', 'Verde', 'Sim'),
	(14, 'A', '200', 'Nao'),
	(14, 'B', '100', 'Sim'),
	(14, 'C', '170', 'Nao'),
	(14, 'D', '220', 'Nao'),
	(15, 'A', '21 de Abril', 'Nao'),
	(15, 'B', '12 de Outubro', 'Nao'),
	(15, 'C', '7 de Setembro', 'Sim'),
	(15, 'D', '25 de Dezembro', 'Nao'),
	(16, 'A', 'Veneza', 'Nao'),
	(16, 'B', 'Vitória', 'Nao'),
	(16, 'C', 'Vancouver', 'Nao'),
	(16, 'D', 'Vaticano', 'Sim'),
	(17, 'A', 'Médicos', 'Nao'),
	(17, 'B', 'Escoteiros', 'Sim'),
	(17, 'C', 'Bombeiros', 'Nao'),
	(17, 'D', 'Policiais', 'Nao'),
	(18, 'A', 'Romeu', 'Sim'),
	(18, 'B', 'Orfeu', 'Nao'),
	(18, 'C', 'Hamlet', 'Nao'),
	(18, 'D', 'Iago', 'Nao'),
	(19, 'A', 'Nove', 'Nao'),
	(19, 'B', 'Dez', 'Nao'),
	(19, 'C', 'Onze', 'Nao'),
	(19, 'D', 'Doze', 'Sim'),
	(20, 'A', 'Paraná', 'Nao'),
	(20, 'B', 'Santa Catarina', 'Nao'),
	(20, 'C', 'São Paulo', 'Nao'),
	(20, 'D', 'Bahia', 'Sim'),
	(21, 'A', 'Cano', 'Nao'),
	(21, 'B', 'Tambor', 'Sim'),
	(21, 'C', 'Agulha', 'Nao'),
	(21, 'D', 'Gatilho', 'Nao'),
	(22, 'A', 'Mônica', 'Nao'),
	(22, 'B', 'Cebolinha', 'Sim'),
	(22, 'C', 'Cascão', 'Nao'),
	(22, 'D', 'Magali', 'Nao'),
	(23, 'A', 'Silvinha', 'Nao'),
	(23, 'B', 'Wanderléia', 'Sim'),
	(23, 'C', 'Gretchen', 'Nao'),
	(23, 'D', 'Martinha', 'Nao'),
	(24, 'A', 'Ceará', 'Nao'),
	(24, 'B', 'Rio Grande Do Sul', 'Sim'),
	(24, 'C', 'Pará', 'Nao'),
	(24, 'D', 'Maranhão', 'Nao'),
	(25, 'A', 'Leonardo', 'Nao'),
	(25, 'B', 'Xororó', 'Sim'),
	(25, 'C', 'Zezé Di Camargo', 'Nao'),
	(25, 'D', 'Chitãozinho', 'Nao'),
	(26, 'A', 'Maurício De Sousa', 'Nao'),
	(26, 'B', 'Ziraldo', 'Nao'),
	(26, 'C', 'Monteiro Lobato', 'Sim'),
	(26, 'D', 'Machado De Assis', 'Nao'),
	(27, 'A', 'Sultão De Brunei', 'Nao'),
	(27, 'B', 'Akio Morita', 'Nao'),
	(27, 'C', 'Bill Gates', 'Sim'),
	(27, 'D', 'Príncipe Charles', 'Nao'),
	(28, 'A', 'Calota', 'Nao'),
	(28, 'B', 'Estepe', 'Sim'),
	(28, 'C', 'Macaco', 'Nao'),
	(28, 'D', 'Chave De Roda', 'Nao'),
	(29, 'A', 'Floquinho', 'Nao'),
	(29, 'B', 'Rin-Tin-Tin', 'Nao'),
	(29, 'C', 'Lassie', 'Nao'),
	(29, 'D', 'Scooby-Doo', 'Sim'),
	(30, 'A', 'Uma', 'Nao'),
	(30, 'B', 'Duas', 'Sim'),
	(30, 'C', 'Três', 'Nao'),
	(30, 'D', 'Quatro', 'Nao'),
	(31, 'A', 'Zagueiro', 'Nao'),
	(31, 'B', 'Goleiro', 'Sim'),
	(31, 'C', 'Atacante', 'Nao'),
	(31, 'D', 'Armador', 'Nao'),
	(32, 'A', 'Esmeralda', 'Nao'),
	(32, 'B', 'Rubi', 'Nao'),
	(32, 'C', 'Pérola', 'Nao'),
	(32, 'D', 'Diamante', 'Sim'),
	(33, 'A', 'Adega', 'Sim'),
	(33, 'B', 'Biblioteca', 'Nao'),
	(33, 'C', 'Sótão', 'Nao'),
	(33, 'D', 'Sala', 'Nao'),
	(34, 'A', 'Frank Sinatra', 'Nao'),
	(34, 'B', 'Little Richard', 'Nao'),
	(34, 'C', 'Elvis Presley', 'Sim'),
	(34, 'D', 'Richie Valens', 'Nao'),
	(35, 'A', 'Félix', 'Nao'),
	(35, 'B', 'Tom', 'Nao'),
	(35, 'C', 'Frajola', 'Sim'),
	(35, 'D', 'Mingau', 'Nao'),
	(36, 'A', 'Tiazinha', 'Nao'),
	(36, 'B', 'Feiticeira', 'Sim'),
	(36, 'C', 'Lady Lu', 'Nao'),
	(36, 'D', 'Sheila Mello', 'Nao'),
	(37, 'A', '364', 'Nao'),
	(37, 'B', '365', 'Nao'),
	(37, 'C', '366', 'Sim'),
	(37, 'D', '367', 'Nao'),
	(38, 'A', 'Sapo', 'Nao'),
	(38, 'B', 'Camaleão', 'Sim'),
	(38, 'C', 'Lagarto', 'Nao'),
	(38, 'D', 'Jacaré', 'Nao'),
	(39, 'A', '45 minutos', 'Sim'),
	(39, 'B', '90 minutos', 'Nao'),
	(39, 'C', '120 minutos', 'Nao'),
	(39, 'D', '150 minutos', 'Nao'),
	(40, 'A', 'Nova York', 'Nao'),
	(40, 'B', 'Las Vegas', 'Nao'),
	(40, 'C', 'New Orleans', 'Nao'),
	(40, 'D', 'Hollywood', 'Sim'),
	(41, 'A', '707', 'Nao'),
	(41, 'B', '907', 'Nao'),
	(41, 'C', '008', 'Nao'),
	(41, 'D', '007', 'Sim'),
	(42, 'A', 'Melancia', 'Nao'),
	(42, 'B', 'Laranja', 'Sim'),
	(42, 'C', 'Maçã', 'Nao'),
	(42, 'D', 'Uva', 'Nao'),
	(43, 'A', 'Dez', 'Nao'),
	(43, 'B', 'Mil', 'Nao'),
	(43, 'C', 'Cem', 'Sim'),
	(43, 'D', 'Cinquenta', 'Nao'),
	(44, 'A', 'Mamão', 'Nao'),
	(44, 'B', 'Maçã', 'Sim'),
	(44, 'C', 'Uva', 'Nao'),
	(44, 'D', 'Abacaxi', 'Nao'),
	(45, 'A', 'Golden Gate', 'Nao'),
	(45, 'B', 'Rio-Niterói', 'Sim'),
	(45, 'C', 'Rio São Franscisco', 'Nao'),
	(45, 'D', 'Brooklin', 'Nao'),
	(46, 'A', '1450', 'Nao'),
	(46, 'B', '1500', 'Sim'),
	(46, 'C', '1550', 'Nao'),
	(46, 'D', '1400', 'Nao'),
	(47, 'A', 'Longitude', 'Nao'),
	(47, 'B', 'Umidade', 'Nao'),
	(47, 'C', 'Temperatura', 'Sim'),
	(47, 'D', 'Latitude', 'Nao'),
	(48, 'A', 'Americano', 'Sim'),
	(48, 'B', 'Africano', 'Nao'),
	(48, 'C', 'Europeu', 'Nao'),
	(48, 'D', 'Asiático', 'Nao'),
	(49, 'A', 'Gepeto', 'Sim'),
	(49, 'B', 'Fada', 'Nao'),
	(49, 'C', 'Bruxa', 'Nao'),
	(49, 'D', 'Gigante', 'Nao'),
	(50, 'A', 'Escudo', 'Nao'),
	(50, 'B', 'Coroa', 'Nao'),
	(50, 'C', 'Dólar', 'Sim'),
	(50, 'D', 'Libra', 'Nao'),
	(51, 'A', 'Dois a zero', 'Nao'),
	(51, 'B', 'Três a zero', 'Sim'),
	(51, 'C', 'Quatro a zero', 'Nao'),
	(51, 'D', 'Cinco a zero', 'Nao'),
	(52, 'A', 'Três', 'Nao'),
	(52, 'B', 'Quatro', 'Sim'),
	(52, 'C', 'Cinco', 'Nao'),
	(52, 'D', 'Seis', 'Nao'),
	(53, 'A', 'Rio De Janeiro', 'Nao'),
	(53, 'B', 'Porto Alegre', 'Nao'),
	(53, 'C', 'Piracicaba', 'Nao'),
	(53, 'D', 'São Paulo', 'Sim'),
	(54, 'A', 'Penadinho', 'Nao'),
	(54, 'B', 'Zé de caixão', 'Sim'),
	(54, 'C', 'Zé do casarão', 'Nao'),
	(54, 'D', 'Toninho do diabo', 'Nao'),
	(55, 'A', 'Sopro', 'Nao'),
	(55, 'B', 'Cordas', 'Sim'),
	(55, 'C', 'Percussão', 'Nao'),
	(55, 'D', 'Repercussão', 'Nao'),
	(56, 'A', 'Maçã', 'Sim'),
	(56, 'B', 'Pêra', 'Nao'),
	(56, 'C', 'Melão', 'Nao'),
	(56, 'D', 'Laranja', 'Nao'),
	(57, 'A', 'Zagallo', 'Sim'),
	(57, 'B', 'Scolari', 'Nao'),
	(57, 'C', 'Luxemburgo', 'Nao'),
	(57, 'D', 'Carpegianni', 'Nao'),
	(58, 'A', 'Belo Horizonte', 'Nao'),
	(58, 'B', 'Rio de Janeiro', 'Nao'),
	(58, 'C', 'São Paulo', 'Sim'),
	(58, 'D', 'Salvador', 'Nao'),
	(59, 'A', 'Geriatria', 'Nao'),
	(59, 'B', 'Pediatria', 'Sim'),
	(59, 'C', 'Infantologia', 'Nao'),
	(59, 'D', 'Biologia', 'Nao'),
	(60, 'A', 'Estados Unidos', 'Nao'),
	(60, 'B', 'Japão', 'Sim'),
	(60, 'C', 'Coréia do Sul', 'Nao'),
	(60, 'D', 'China', 'Nao'),
	(61, 'A', 'Uma', 'Sim'),
	(61, 'B', 'Duas', 'Nao'),
	(61, 'C', 'Três', 'Nao'),
	(61, 'D', 'Quatro', 'Nao'),
	(62, 'A', '18', 'Nao'),
	(62, 'B', '24', 'Nao'),
	(62, 'C', '32', 'Sim'),
	(62, 'D', '36', 'Nao'),
	(63, 'A', 'Dunga', 'Nao'),
	(63, 'B', 'Zangado', 'Nao'),
	(63, 'C', 'Dengoso', 'Nao'),
	(63, 'D', 'Mestre', 'Sim'),
	(64, 'A', 'Batman', 'Nao'),
	(64, 'B', 'Huck', 'Nao'),
	(64, 'C', 'He-Man', 'Nao'),
	(64, 'D', 'Super-Homem', 'Sim'),
	(65, 'A', 'Damas', 'Nao'),
	(65, 'B', 'Xadrez', 'Sim'),
	(65, 'C', 'Ludo', 'Nao'),
	(65, 'D', 'Dominó', 'Nao'),
	(66, 'A', 'Flor', 'Nao'),
	(66, 'B', 'Fruto', 'Nao'),
	(66, 'C', 'Pedra', 'Sim'),
	(66, 'D', 'Verdura', 'Nao'),
	(67, 'A', 'São Pedro', 'Nao'),
	(67, 'B', 'São Paulo', 'Nao'),
	(67, 'C', 'São João', 'Nao'),
	(67, 'D', 'Santo Antônio', 'Sim'),
	(68, 'A', 'Adib Jatene', 'Nao'),
	(68, 'B', 'José Serra', 'Sim'),
	(68, 'C', 'Ciro Gomes', 'Nao'),
	(68, 'D', 'Pedro Malan', 'Nao'),
	(69, 'A', 'Adão', 'Nao'),
	(69, 'B', 'Isaac', 'Nao'),
	(69, 'C', 'Abel', 'Sim'),
	(69, 'D', 'Abraão', 'Nao'),
	(70, 'A', 'Bíblia', 'Sim'),
	(70, 'B', 'Enciclopédia', 'Nao'),
	(70, 'C', 'Dicionário', 'Nao'),
	(70, 'D', 'Atlas', 'Nao'),
	(71, 'A', 'Guarda-Chuva', 'Sim'),
	(71, 'B', 'Chapéu', 'Nao'),
	(71, 'C', 'Galocha', 'Nao'),
	(71, 'D', 'Capa', 'Nao'),
	(72, 'A', 'Sereia', 'Sim'),
	(72, 'B', 'Medusa', 'Nao'),
	(72, 'C', 'Cleópatra', 'Nao'),
	(72, 'D', 'Serena', 'Nao'),
	(73, 'A', 'Revolução Francesa', 'Nao'),
	(73, 'B', 'Guerra dos Emboabas', 'Nao'),
	(73, 'C', 'Inconfidência Mineira', 'Sim'),
	(73, 'D', 'Segunda Guerra Mundial', 'Nao'),
	(74, 'A', 'América', 'Nao'),
	(74, 'B', 'Holanda', 'Nao'),
	(74, 'C', 'França', 'Sim'),
	(74, 'D', 'Suécia', 'Nao'),
	(75, 'A', 'Diamante', 'Nao'),
	(75, 'B', 'Pérola', 'Sim'),
	(75, 'C', 'Rubi', 'Nao'),
	(75, 'D', 'Esmeralda', 'Nao'),
	(76, 'A', '26 de Dezembro', 'Nao'),
	(76, 'B', '7 de Setembro', 'Nao'),
	(76, 'C', '1 de Abril', 'Sim'),
	(76, 'D', '15 de Novembro', 'Nao'),
	(77, 'A', 'Paraíba', 'Sim'),
	(77, 'B', 'Ceará', 'Nao'),
	(77, 'C', 'Bahia', 'Nao'),
	(77, 'D', 'Alagoas', 'Nao'),
	(78, 'A', '12 de Outubro', 'Sim'),
	(78, 'B', '1 de Abril', 'Nao'),
	(78, 'C', '13 de Maio', 'Nao'),
	(78, 'D', '9 de Julho', 'Nao'),
	(79, 'A', 'Da Selva', 'Sim'),
	(79, 'B', 'Da Noite', 'Nao'),
	(79, 'C', 'Da Tasmânia', 'Nao'),
	(79, 'D', 'Das Mulheres', 'Nao'),
	(80, 'A', 'Diana', 'Nao'),
	(80, 'B', 'Louis Laine', 'Nao'),
	(80, 'C', 'Jane', 'Sim'),
	(80, 'D', 'Chita', 'Nao'),
	(81, 'A', 'Cavalo', 'Nao'),
	(81, 'B', 'Rena', 'Sim'),
	(81, 'C', 'Touro', 'Nao'),
	(81, 'D', 'Jumento', 'Nao'),
	(82, 'A', 'Espírito Santo', 'Sim'),
	(82, 'B', 'Rio Grande Do Norte', 'Nao'),
	(82, 'C', 'Santa Catarina', 'Nao'),
	(82, 'D', 'Paraná', 'Nao'),
	(83, 'A', 'Cinco', 'Nao'),
	(83, 'B', 'Seis', 'Sim'),
	(83, 'C', 'Sete', 'Nao'),
	(83, 'D', 'Oito', 'Nao'),
	(84, 'A', 'Condutor', 'Nao'),
	(84, 'B', 'Operador', 'Nao'),
	(84, 'C', 'Ascensorista', 'Sim'),
	(84, 'D', 'Recepcionista', 'Nao'),
	(85, 'A', 'Dez', 'Nao'),
	(85, 'B', 'Onze', 'Nao'),
	(85, 'C', 'Doze', 'Sim'),
	(85, 'D', 'Treze', 'Nao'),
	(86, 'A', 'Estados Unidos', 'Nao'),
	(86, 'B', 'Inglaterra', 'Nao'),
	(86, 'C', 'Itália', 'Sim'),
	(86, 'D', 'Espanha', 'Nao'),
	(87, 'A', 'Engenheiro', 'Nao'),
	(87, 'B', 'Mecânico', 'Nao'),
	(87, 'C', 'Médico', 'Sim'),
	(87, 'D', 'Aviador', 'Nao'),
	(88, 'A', 'Administração', 'Nao'),
	(88, 'B', 'Economia', 'Nao'),
	(88, 'C', 'Direito', 'Nao'),
	(88, 'D', 'Sociologia', 'Sim'),
	(89, 'A', 'Setembro', 'Nao'),
	(89, 'B', 'Junho', 'Nao'),
	(89, 'C', 'Maio', 'Sim'),
	(89, 'D', 'Outubro', 'Nao'),
	(90, 'A', 'Graham Bell', 'Sim'),
	(90, 'B', 'George Washington', 'Nao'),
	(90, 'C', 'Thomas Edison', 'Nao'),
	(90, 'D', 'Marconi', 'Nao'),
	(91, 'A', 'Automobilismo', 'Nao'),
	(91, 'B', 'Iatismo', 'Nao'),
	(91, 'C', 'Aeromodelismo', 'Sim'),
	(91, 'D', 'Atletismo', 'Nao'),
	(92, 'A', 'Bom-Dia', 'Nao'),
	(92, 'B', 'Até Logo', 'Nao'),
	(92, 'C', 'Eu Amo Você', 'Sim'),
	(92, 'D', 'Estou com fome', 'Nao'),
	(93, 'A', 'Robin Cook', 'Nao'),
	(93, 'B', 'Robin Banks', 'Nao'),
	(93, 'C', 'Robin Hood', 'Sim'),
	(93, 'D', 'Robin Days', 'Nao'),
	(94, 'A', 'Azul', 'Nao'),
	(94, 'B', 'Verde', 'Nao'),
	(94, 'C', 'Amarela', 'Nao'),
	(94, 'D', 'Vermelha', 'Sim'),
	(95, 'A', 'Alface', 'Nao'),
	(95, 'B', 'Espinafre', 'Sim'),
	(95, 'C', 'Cenoura', 'Nao'),
	(95, 'D', 'Repolho', 'Nao'),
	(96, 'A', '12 de Agosto', 'Nao'),
	(96, 'B', '11 de Janeiro', 'Nao'),
	(96, 'C', '7 de Setembro', 'Nao'),
	(96, 'D', '13 de Junho', 'Sim'),
	(97, 'A', 'Engraxate', 'Nao'),
	(97, 'B', 'Pedreiro', 'Nao'),
	(97, 'C', 'Feirante', 'Nao'),
	(97, 'D', 'Metalúrgico', 'Sim'),
	(98, 'A', 'Sherazarde', 'Nao'),
	(98, 'B', 'Lady Godiva', 'Nao'),
	(98, 'C', 'Cleópatra', 'Sim'),
	(98, 'D', 'Julieta', 'Nao'),
	(99, 'A', 'Verão', 'Nao'),
	(99, 'B', 'Outono', 'Sim'),
	(99, 'C', 'Inverno', 'Nao'),
	(99, 'D', 'Primavera', 'Nao'),
	(100, 'A', 'Enforcada', 'Nao'),
	(100, 'B', 'Afogada', 'Nao'),
	(100, 'C', 'Queimada', 'Sim'),
	(100, 'D', 'Asfixiada', 'Nao'),
	(101, 'A', 'Seis', 'Nao'),
	(101, 'B', 'Oito', 'Nao'),
	(101, 'C', 'Dez', 'Nao'),
	(101, 'D', 'Doze', 'Sim'),
	(102, 'A', 'Uruguai', 'Nao'),
	(102, 'B', 'Argentina', 'Sim'),
	(102, 'C', 'Paraguai', 'Nao'),
	(102, 'D', 'Espanha', 'Nao'),
	(103, 'A', 'Trajano', 'Nao'),
	(103, 'B', 'Nero', 'Sim'),
	(103, 'C', 'Brutus', 'Nao'),
	(103, 'D', 'Calígula', 'Nao'),
	(104, 'A', 'Japão', 'Nao'),
	(104, 'B', 'México', 'Nao'),
	(104, 'C', 'Itália', 'Sim'),
	(104, 'D', 'Estados Unidos', 'Nao'),
	(105, 'A', 'Milanense', 'Nao'),
	(105, 'B', 'Milanoso', 'Nao'),
	(105, 'C', 'Milista', 'Nao'),
	(105, 'D', 'Milanês', 'Sim'),
	(106, 'A', 'Carpinteiro', 'Sim'),
	(106, 'B', 'Relojoeiro', 'Nao'),
	(106, 'C', 'Confeiteiro', 'Nao'),
	(106, 'D', 'Bombeiro', 'Nao'),
	(107, 'A', 'Morumbi', 'Nao'),
	(107, 'B', 'Pacaembu', 'Nao'),
	(107, 'C', 'Maracanã', 'Sim'),
	(107, 'D', 'Mineirão', 'Nao'),
	(108, 'A', 'Vulcão', 'Nao'),
	(108, 'B', 'Comida ', 'Nao'),
	(108, 'C', 'Instrumento musical', 'Sim'),
	(108, 'D', 'Tribo indígena ', 'Nao'),
	(109, 'A', 'Camicases', 'Sim'),
	(109, 'B', 'Sashimis ', 'Nao'),
	(109, 'C', 'Haraquiris', 'Nao'),
	(109, 'D', 'Sumós', 'Nao'),
	(110, 'A', 'Embracação', 'Sim'),
	(110, 'B', 'Brinquedo', 'Nao'),
	(110, 'C', 'Música', 'Nao'),
	(110, 'D', 'Símbolo', 'Nao'),
	(111, 'A', 'Japão', 'Sim'),
	(111, 'B', 'China', 'Nao'),
	(111, 'C', 'Ìndia ', 'Nao'),
	(111, 'D', 'Indonésia', 'Nao'),
	(112, 'A', 'Primeira Dama ', 'Nao'),
	(112, 'B', 'Dona Prima', 'Nao'),
	(112, 'C', 'Prima Dona ', 'Sim'),
	(112, 'D', 'Obra Prima ', 'Nao'),
	(113, 'A', 'Inseto', 'Nao'),
	(113, 'B', 'Àrvore ', 'Sim'),
	(113, 'C', 'Verme', 'Nao'),
	(113, 'D', 'Verdura', 'Nao'),
	(114, 'A', 'Mar', 'Nao'),
	(114, 'B', 'Montanha', 'Sim'),
	(114, 'C', 'Rio ', 'Nao'),
	(114, 'D', 'Praia', 'Nao'),
	(115, 'A', 'Paris ', 'Nao'),
	(115, 'B', 'Copenhague', 'Nao'),
	(115, 'C', 'Roma ', 'Sim'),
	(115, 'D', 'Londres ', 'Nao'),
	(116, 'A', 'Everest', 'Sim'),
	(116, 'B', 'Monte Sinai', 'Nao'),
	(116, 'C', 'Monte Castelo', 'Nao'),
	(116, 'D', 'Monte Blanc', 'Nao'),
	(117, 'A', 'Tâmisa', 'Sim'),
	(117, 'B', 'Sena ', 'Nao'),
	(117, 'C', 'Reno', 'Nao'),
	(117, 'D', 'Aube ', 'Nao'),
	(118, 'A', 'Fila ', 'Nao'),
	(118, 'B', 'Pastor alemão', 'Nao'),
	(118, 'C', 'Poodle', 'Nao'),
	(118, 'D', 'São-Bernardo', 'Sim'),
	(119, 'A', 'Nelson Piquet', 'Nao'),
	(119, 'B', 'Nelson Mandela', 'Sim'),
	(119, 'C', 'Nelson Ned', 'Nao'),
	(119, 'D', 'John Nelson', 'Nao'),
	(120, 'A', 'Orlando silva ', 'Nao'),
	(120, 'B', 'Vicente celestino', 'Nao'),
	(120, 'C', 'Francisco alves ', 'Sim'),
	(120, 'D', 'Carlos galhardo', 'Nao'),
	(121, 'A', '18', 'Nao'),
	(121, 'B', '20', 'Nao'),
	(121, 'C', '24', 'Sim'),
	(121, 'D', '30', 'Nao'),
	(122, 'A', 'Onu', 'Sim'),
	(122, 'B', 'Fmi', 'Nao'),
	(122, 'C', 'Cia', 'Nao'),
	(122, 'D', 'Otan', 'Nao'),
	(123, 'A', '57 Anos ', 'Nao'),
	(123, 'B', '67 Anos', 'Nao'),
	(123, 'C', '76 Anos', 'Sim'),
	(123, 'D', '79 Anos ', 'Nao'),
	(124, 'A', 'Do coroinha', 'Nao'),
	(124, 'B', 'Do padre ', 'Sim'),
	(124, 'C', 'Do sacristão', 'Nao'),
	(124, 'D', 'Do bispo ', 'Nao'),
	(125, 'A', 'Cameron diaz', 'Nao'),
	(125, 'B', 'Kate winslet', 'Sim'),
	(125, 'C', 'Bridget fonda ', 'Nao'),
	(125, 'D', 'Catherine zetta jones ', 'Nao'),
	(126, 'A', 'Astiguimatismo ', 'Nao'),
	(126, 'B', 'Tendinite ', 'Nao'),
	(126, 'C', 'Vitiligo', 'Sim'),
	(126, 'D', 'Vitiniga', 'Nao'),
	(127, 'A', 'Dr.Zerbini ', 'Nao'),
	(127, 'B', 'Dr.Fritz', 'Nao'),
	(127, 'C', 'Dr.Jatene', 'Sim'),
	(127, 'D', 'Dr.Calligari', 'Nao'),
	(128, 'A', 'Bill', 'Nao'),
	(128, 'B', 'Clyde', 'Sim'),
	(128, 'C', 'James', 'Nao'),
	(128, 'D', 'Butch', 'Nao'),
	(129, 'A', 'Lira', 'Nao'),
	(129, 'B', 'Março', 'Sim'),
	(129, 'C', 'Franco', 'Nao'),
	(129, 'D', 'Libra', 'Nao'),
	(130, 'A', 'Jack ruby', 'Sim'),
	(130, 'B', 'John Wilkes Booth', 'Nao'),
	(130, 'C', 'Pat Garret ', 'Nao'),
	(130, 'D', 'Charlotte Corday', 'Nao'),
	(131, 'A', 'Sancho pança ', 'Sim'),
	(131, 'B', 'Guilherme Tell', 'Nao'),
	(131, 'C', 'Sigmuno Freud ', 'Nao'),
	(131, 'D', 'Lancelot', 'Nao'),
	(132, 'A', 'Piu-Piu', 'Nao'),
	(132, 'B', 'Woodstock', 'Sim'),
	(132, 'C', 'Canarinho', 'Nao'),
	(132, 'D', 'Rouxinol', 'Nao'),
	(133, 'A', 'Ferro', 'Nao'),
	(133, 'B', 'Cobre', 'Sim'),
	(133, 'C', 'Mercúrio', 'Nao'),
	(133, 'D', 'Aço', 'Nao'),
	(134, 'A', 'Papiro', 'Sim'),
	(134, 'B', 'Eucalipto', 'Nao'),
	(134, 'C', 'Oliveira', 'Nao'),
	(134, 'D', 'Milho', 'Nao'),
	(135, 'A', 'Espanha', 'Sim'),
	(135, 'B', 'Itália', 'Nao'),
	(135, 'C', 'França', 'Nao'),
	(135, 'D', 'Alemanha', 'Nao'),
	(136, 'A', 'Lilico', 'Nao'),
	(136, 'B', 'Roni Cócegas', 'Sim'),
	(136, 'C', 'Grande Otelo', 'Nao'),
	(136, 'D', 'Mazzaropi', 'Nao'),
	(137, 'A', 'Quadros', 'Nao'),
	(137, 'B', 'Moedas', 'Nao'),
	(137, 'C', 'Selos', 'Sim'),
	(137, 'D', 'Figurinhas', 'Nao'),
	(138, 'A', 'Leonardo Da Vinci', 'Sim'),
	(138, 'B', 'Ticiano', 'Nao'),
	(138, 'C', 'Rafael', 'Nao'),
	(138, 'D', 'Michelangelo', 'Nao'),
	(139, 'A', 'Moscou', 'Sim'),
	(139, 'B', 'Berlim', 'Nao'),
	(139, 'C', 'Paris', 'Nao'),
	(139, 'D', 'Roma', 'Nao'),
	(140, 'A', 'Vênus', 'Nao'),
	(140, 'B', 'Vesúvio', 'Sim'),
	(140, 'C', 'Varsóvia', 'Nao'),
	(140, 'D', 'Veneza', 'Nao'),
	(141, 'A', '1914-1919', 'Sim'),
	(141, 'B', '1939-1945', 'Nao'),
	(141, 'C', '1921-1932', 'Nao'),
	(141, 'D', '1912-1915', 'Nao'),
	(142, 'A', 'V', 'Nao'),
	(142, 'B', 'D', 'Nao'),
	(142, 'C', 'L', 'Nao'),
	(142, 'D', 'X', 'Sim'),
	(143, 'A', 'Titanic', 'Nao'),
	(143, 'B', 'Sexta-Feira Treze', 'Nao'),
	(143, 'C', 'O poderoso Chefão', 'Sim'),
	(143, 'D', 'Guerra nas Estrelas', 'Nao'),
	(144, 'A', 'Camelos', 'Nao'),
	(144, 'B', 'Búfalos', 'Nao'),
	(144, 'C', 'Carneiros', 'Nao'),
	(144, 'D', 'Porcos', 'Sim'),
	(145, 'A', 'Clint Eastwood', 'Nao'),
	(145, 'B', 'Steven Spielberg', 'Sim'),
	(145, 'C', 'Stanley Kubrick', 'Nao'),
	(145, 'D', 'Pedro Almodóvar', 'Nao'),
	(146, 'A', 'Paraná', 'Nao'),
	(146, 'B', 'Açúcar', 'Nao'),
	(146, 'C', 'Chocolate', 'Sim'),
	(146, 'D', 'Café', 'Nao'),
	(147, 'A', 'Pelé', 'Nao'),
	(147, 'B', 'João Havelange', 'Nao'),
	(147, 'C', 'Charles Miller', 'Sim'),
	(147, 'D', 'Paulo Machado', 'Nao'),
	(148, 'A', 'Africano', 'Sim'),
	(148, 'B', 'Europeu', 'Nao'),
	(148, 'C', 'Americano', 'Nao'),
	(148, 'D', 'Asíatico', 'Nao'),
	(149, 'A', 'Pequim', 'Nao'),
	(149, 'B', 'Hanói', 'Nao'),
	(149, 'C', 'Hiroshima', 'Nao'),
	(149, 'D', 'Hong kong', 'Sim'),
	(150, 'A', 'Índia', 'Sim'),
	(150, 'B', 'Islândia', 'Nao'),
	(150, 'C', 'Paquistão', 'Nao'),
	(150, 'D', 'México', 'Nao'),
	(151, 'A', 'Veias', 'Nao'),
	(151, 'B', 'Músculos', 'Nao'),
	(151, 'C', 'Artérias', 'Sim'),
	(151, 'D', 'Ossos', 'Nao'),
	(152, 'A', 'Pirarucu', 'Nao'),
	(152, 'B', 'Perneta', 'Nao'),
	(152, 'C', 'Pirata', 'Sim'),
	(152, 'D', 'Papagaio', 'Nao'),
	(153, 'A', 'Matemática', 'Sim'),
	(153, 'B', 'Biologia', 'Nao'),
	(153, 'C', 'Química', 'Nao'),
	(153, 'D', 'Física', 'Nao'),
	(154, 'A', 'Masters e Johnson', 'Nao'),
	(154, 'B', 'Dr. Jekyll e Mr. Hyde', 'Sim'),
	(154, 'C', 'Bonnie e Clyde', 'Nao'),
	(154, 'D', 'D. Quixote e Sancho Pança', 'Nao'),
	(155, 'A', 'Glenda Jackson', 'Nao'),
	(155, 'B', 'Margaret Becket', 'Nao'),
	(155, 'C', 'Marilyn Monroe', 'Sim'),
	(155, 'D', 'Elizabeth Taylor', 'Nao'),
	(156, 'A', 'Júlio César', 'Sim'),
	(156, 'B', 'Calígula', 'Nao'),
	(156, 'C', 'Nero', 'Nao'),
	(156, 'D', 'Marco Antônio', 'Nao'),
	(157, 'A', 'Pororoca', 'Nao'),
	(157, 'B', 'Perereca', 'Nao'),
	(157, 'C', 'Pirapora', 'Nao'),
	(157, 'D', 'Piracema', 'Sim'),
	(158, 'A', 'Itália', 'Nao'),
	(158, 'B', 'Uruguai', 'Nao'),
	(158, 'C', 'Argentina', 'Nao'),
	(158, 'D', 'Brasil', 'Sim'),
	(159, 'A', 'Ouros e Copas', 'Sim'),
	(159, 'B', 'Copas e Paus', 'Nao'),
	(159, 'C', 'Paus e Ouros', 'Nao'),
	(159, 'D', 'Espadas e Paus', 'Nao'),
	(160, 'A', 'Bruce Wayne', 'Sim'),
	(160, 'B', 'Dexter', 'Nao'),
	(160, 'C', 'Clark Kent', 'Nao'),
	(160, 'D', 'Lex Lutor', 'Nao'),
	(161, 'A', 'Síria', 'Nao'),
	(161, 'B', 'Nepal', 'Nao'),
	(161, 'C', 'Mongólia', 'Nao'),
	(161, 'D', 'Líbano', 'Sim'),
	(162, 'A', 'Tanque', 'Nao'),
	(162, 'B', 'Navio de Guerra', 'Sim'),
	(162, 'C', 'Dirigível', 'Nao'),
	(162, 'D', 'Avião de Caça', 'Nao'),
	(163, 'A', 'Cambuci', 'Nao'),
	(163, 'B', 'Sacomã', 'Nao'),
	(163, 'C', 'Ipiranga', 'Sim'),
	(163, 'D', 'São Francisco', 'Nao'),
	(164, 'A', 'Baseball', 'Nao'),
	(164, 'B', 'Basquete', 'Nao'),
	(164, 'C', 'Futebol Americano', 'Sim'),
	(164, 'D', 'Golf', 'Nao'),
	(165, 'A', 'Submarino', 'Nao'),
	(165, 'B', 'Jet Ski', 'Nao'),
	(165, 'C', 'Jangada', 'Sim'),
	(165, 'D', 'Lancha', 'Nao'),
	(166, 'A', 'Alasca', 'Nao'),
	(166, 'B', 'Nova York', 'Nao'),
	(166, 'C', 'Flórida', 'Sim'),
	(166, 'D', 'Califórnia', 'Nao'),
	(167, 'A', 'Belém', 'Nao'),
	(167, 'B', 'Bagdá', 'Sim'),
	(167, 'C', 'Beirute', 'Nao'),
	(167, 'D', 'Budapeste', 'Nao'),
	(168, 'A', 'Rolo Compressor', 'Sim'),
	(168, 'B', 'Escavadeira', 'Nao'),
	(168, 'C', 'Trator', 'Nao'),
	(168, 'D', 'Lixadeira', 'Nao'),
	(169, 'A', 'Michael Jordan', 'Nao'),
	(169, 'B', 'Magic Johnson', 'Sim'),
	(169, 'C', 'Dennis Rodman', 'Nao'),
	(169, 'D', 'Mike Tyson', 'Nao'),
	(170, 'A', 'Pluto', 'Nao'),
	(170, 'B', 'Floquinho', 'Nao'),
	(170, 'C', 'Baleia', 'Nao'),
	(170, 'D', 'Snoopy', 'Sim'),
	(171, 'A', 'Ronald Reagan', 'Sim'),
	(171, 'B', 'George Bush', 'Nao'),
	(171, 'C', 'Richard Nixon', 'Nao'),
	(171, 'D', 'Bill Clinton', 'Nao'),
	(172, 'A', 'Igreja', 'Nao'),
	(172, 'B', 'Capela', 'Nao'),
	(172, 'C', 'Sinagoga', 'Sim'),
	(172, 'D', 'Catedral', 'Nao'),
	(173, 'A', 'Molusco', 'Nao'),
	(173, 'B', 'Crustáceo', 'Nao'),
	(173, 'C', 'Peixe', 'Sim'),
	(173, 'D', 'Mamífero', 'Nao'),
	(174, 'A', 'Inglaterra', 'Nao'),
	(174, 'B', 'Estados Unidos', 'Sim'),
	(174, 'C', 'Canadá', 'Nao'),
	(174, 'D', 'França', 'Nao'),
	(175, 'A', 'São José do Rio Preto', 'Nao'),
	(175, 'B', 'São José dos Pinhais', 'Nao'),
	(175, 'C', 'São José dos Campos', 'Sim'),
	(175, 'D', 'São José dos Santos', 'Nao'),
	(176, 'A', 'Munique', 'Nao'),
	(176, 'B', 'Sidney', 'Sim'),
	(176, 'C', 'Tóquio', 'Nao'),
	(176, 'D', 'Atlanta', 'Nao'),
	(177, 'A', 'Japão', 'Nao'),
	(177, 'B', 'China', 'Sim'),
	(177, 'C', 'Afeganistão', 'Nao'),
	(177, 'D', 'Índia', 'Nao'),
	(178, 'A', 'Tiradentes', 'Nao'),
	(178, 'B', 'José Bonifácio', 'Sim'),
	(178, 'C', 'Dom Pedro II', 'Nao'),
	(178, 'D', 'Vasco da Gama', 'Nao'),
	(179, 'A', 'Américo dos Reis', 'Nao'),
	(179, 'B', 'Américo Brasilience', 'Nao'),
	(179, 'C', 'Américo Vespúcio', 'Sim'),
	(179, 'D', 'José Américo da Silva', 'Nao'),
	(180, 'A', 'Ortopedista', 'Nao'),
	(180, 'B', 'Cardiologista', 'Sim'),
	(180, 'C', 'Dermatologista', 'Nao'),
	(180, 'D', 'Acupunturista', 'Nao'),
	(181, 'A', 'Ato intencional', 'Nao'),
	(181, 'B', 'Ato institucional', 'Sim'),
	(181, 'C', 'Ato inspirador', 'Nao'),
	(181, 'D', 'Ato idealizador', 'Nao'),
	(182, 'A', 'Abraão', 'Nao'),
	(182, 'B', 'Moisés', 'Sim'),
	(182, 'C', 'Josué', 'Nao'),
	(182, 'D', 'Elias', 'Nao'),
	(183, 'A', 'Urutu', 'Nao'),
	(183, 'B', 'Cascavel', 'Nao'),
	(183, 'C', 'Jararaca', 'Nao'),
	(183, 'D', 'Píton', 'Sim'),
	(184, 'A', 'Camelo', 'Nao'),
	(184, 'B', 'Cavalo', 'Sim'),
	(184, 'C', 'Macaco', 'Nao'),
	(184, 'D', 'Cachorro', 'Nao'),
	(185, 'A', '1971', 'Nao'),
	(185, 'B', '1972', 'Nao'),
	(185, 'C', '1973', 'Nao'),
	(185, 'D', '1974', 'Sim'),
	(186, 'A', 'Tocantins', 'Nao'),
	(186, 'B', 'Piauí', 'Sim'),
	(186, 'C', 'Acre', 'Nao'),
	(186, 'D', 'Paraná', 'Nao'),
	(187, 'A', 'Tóquio', 'Nao'),
	(187, 'B', 'Nagasaki', 'Nao'),
	(187, 'C', 'Osaka', 'Nao'),
	(187, 'D', 'Hiroxima', 'Sim'),
	(188, 'A', 'Sentir dor', 'Nao'),
	(188, 'B', 'Sentir paladar', 'Nao'),
	(188, 'C', 'Diferenciar cores', 'Sim'),
	(188, 'D', 'Sentir cheiro', 'Nao'),
	(189, 'A', '12 de Outubro', 'Sim'),
	(189, 'B', '12 de Novembro', 'Nao'),
	(189, 'C', '11 de Dezembro', 'Nao'),
	(189, 'D', '1 de Janeiro', 'Nao'),
	(190, 'A', 'Cuibá', 'Nao'),
	(190, 'B', 'Várzea Grande', 'Nao'),
	(190, 'C', 'Rondonópolis', 'Nao'),
	(190, 'D', 'Campo Grande', 'Sim'),
	(191, 'A', 'Cinco', 'Sim'),
	(191, 'B', 'Sete', 'Nao'),
	(191, 'C', 'Três', 'Nao'),
	(191, 'D', 'Quatro', 'Nao'),
	(192, 'A', 'Sulistas', 'Nao'),
	(192, 'B', 'Esquimós', 'Sim'),
	(192, 'C', 'Nortistas', 'Nao'),
	(192, 'D', 'Polares', 'Nao'),
	(193, 'A', 'NaCl', 'Nao'),
	(193, 'B', 'H2', 'Nao'),
	(193, 'C', 'H2O', 'Sim'),
	(193, 'D', 'CO2', 'Nao'),
	(194, 'A', 'Cantora', 'Nao'),
	(194, 'B', 'Escritora', 'Sim'),
	(194, 'C', 'Arquiteta', 'Nao'),
	(194, 'D', 'Pianista', 'Nao'),
	(195, 'A', 'Londres', 'Sim'),
	(195, 'B', 'Nova York', 'Nao'),
	(195, 'C', 'Montreal', 'Nao'),
	(195, 'D', 'Califórnia', 'Nao'),
	(196, 'A', 'Leonardo', 'Nao'),
	(196, 'B', 'Chitãozinho', 'Nao'),
	(196, 'C', 'Daniel', 'Sim'),
	(196, 'D', 'Vinny', 'Nao'),
	(197, 'A', 'Três', 'Nao'),
	(197, 'B', 'Quatro', 'Sim'),
	(197, 'C', 'Cinco', 'Nao'),
	(197, 'D', 'Seis', 'Nao'),
	(198, 'A', 'D.Pedro II', 'Sim'),
	(198, 'B', 'D.Pedro I', 'Nao'),
	(198, 'C', 'D.João VI', 'Nao'),
	(198, 'D', 'Deodoro da Fonseca', 'Nao'),
	(199, 'A', 'Bruno Barreto', 'Nao'),
	(199, 'B', 'Héctor Babenco', 'Nao'),
	(199, 'C', 'Arnaldo Jabor', 'Nao'),
	(199, 'D', 'Walter Salles Júnior', 'Sim'),
	(200, 'A', 'Correio rápido', 'Nao'),
	(200, 'B', 'Correio eletrônico', 'Sim'),
	(200, 'C', 'Correio elegante', 'Nao'),
	(200, 'D', 'Correio de máquina', 'Nao'),
	(201, 'A', 'Andorinha', 'Nao'),
	(201, 'B', 'Pato Selvagem', 'Nao'),
	(201, 'C', 'Pinguim', 'Sim'),
	(201, 'D', 'Marreco', 'Nao'),
	(202, 'A', 'Alemanha', 'Nao'),
	(202, 'B', 'Brasil', 'Nao'),
	(202, 'C', 'Venezuela', 'Nao'),
	(202, 'D', 'Israel', 'Sim'),
	(203, 'A', 'Paquistão', 'Nao'),
	(203, 'B', 'Japão', 'Nao'),
	(203, 'C', 'Tailândia', 'Nao'),
	(203, 'D', 'Egito', 'Sim'),
	(204, 'A', 'Arnold Schwarzenegger', 'Nao'),
	(204, 'B', 'Sylvester Stallone', 'Nao'),
	(204, 'C', 'Steven Seagal', 'Nao'),
	(204, 'D', 'Jean Claude Van Damme', 'Sim'),
	(205, 'A', 'Cannes', 'Nao'),
	(205, 'B', 'Normandia', 'Sim'),
	(205, 'C', 'Capri', 'Nao'),
	(205, 'D', 'Marselha', 'Nao'),
	(206, 'A', 'Polônia', 'Nao'),
	(206, 'B', 'França', 'Nao'),
	(206, 'C', 'Itália', 'Nao'),
	(206, 'D', 'Holada', 'Sim'),
	(207, 'A', 'Delta', 'Nao'),
	(207, 'B', 'Beta', 'Nao'),
	(207, 'C', 'Alfa', 'Sim'),
	(207, 'D', 'Gama', 'Nao'),
	(208, 'A', 'Costa e Silva', 'Sim'),
	(208, 'B', 'Ernesto Geisel', 'Nao'),
	(208, 'C', 'João Figueiredo', 'Nao'),
	(208, 'D', 'Itamari Franco', 'Nao'),
	(209, 'A', 'Conversão', 'Nao'),
	(209, 'B', 'Involução', 'Nao'),
	(209, 'C', 'Reestruturação', 'Sim'),
	(209, 'D', 'Regressão', 'Nao'),
	(210, 'A', '10 Onças', 'Nao'),
	(210, 'B', '10 Gramas', 'Sim'),
	(210, 'C', '10 Quilos', 'Nao'),
	(210, 'D', '10 Libras', 'Nao'),
	(211, 'A', 'Hinduísmo', 'Sim'),
	(211, 'B', 'Xintoísmo', 'Nao'),
	(211, 'C', 'Budismo', 'Nao'),
	(211, 'D', 'Islamismo', 'Nao'),
	(212, 'A', 'Berlim', 'Nao'),
	(212, 'B', 'Nurembergue', 'Sim'),
	(212, 'C', 'Munique', 'Nao'),
	(212, 'D', 'Paris', 'Nao'),
	(213, 'A', 'Asinino', 'Nao'),
	(213, 'B', 'Caprino', 'Sim'),
	(213, 'C', 'Bufalino', 'Nao'),
	(213, 'D', 'Muar', 'Nao'),
	(214, 'A', 'Atlântico', 'Nao'),
	(214, 'B', 'Pacífico', 'Sim'),
	(214, 'C', 'Índico', 'Nao'),
	(214, 'D', 'Ártico', 'Nao'),
	(215, 'A', 'Fernando Collor', 'Nao'),
	(215, 'B', 'João Figueiredo', 'Sim'),
	(215, 'C', 'Tancredo Neves', 'Nao'),
	(215, 'D', 'João Goulart', 'Nao'),
	(216, 'A', 'Guerra Fria', 'Sim'),
	(216, 'B', 'Guerra Do Vietnã', 'Nao'),
	(216, 'C', 'Guerra nas Estrelas', 'Nao'),
	(216, 'D', 'Guerra Da Coréia', 'Nao'),
	(217, 'A', 'No pescoço', 'Nao'),
	(217, 'B', 'No ombro', 'Sim'),
	(217, 'C', 'Na cabeça', 'Nao'),
	(217, 'D', 'No braço', 'Nao'),
	(218, 'A', 'Truman Capote', 'Sim'),
	(218, 'B', 'Henry James', 'Nao'),
	(218, 'C', 'John Steinbeck', 'Nao'),
	(218, 'D', 'Toni Morrison', 'Nao'),
	(219, 'A', 'Ernest Hemingway', 'Nao'),
	(219, 'B', 'Marcel Proust', 'Nao'),
	(219, 'C', 'T.S Elliot', 'Nao'),
	(219, 'D', 'James Joyce', 'Sim'),
	(220, 'A', 'Rr', 'Nao'),
	(220, 'B', 'Rd', 'Nao'),
	(220, 'C', 'Rn', 'Sim'),
	(220, 'D', 'Ro', 'Nao'),
	(221, 'A', 'Células', 'Nao'),
	(221, 'B', 'Nervos', 'Nao'),
	(221, 'C', 'Membranas', 'Sim'),
	(221, 'D', 'Músculos', 'Nao'),
	(222, 'A', 'Álcool', 'Nao'),
	(222, 'B', 'Petróleo', 'Sim'),
	(222, 'C', 'Ouro', 'Nao'),
	(222, 'D', 'Alumínio', 'Nao'),
	(223, 'A', 'Cometa', 'Sim'),
	(223, 'B', 'Meteorito', 'Nao'),
	(223, 'C', 'Camada de Ozônio', 'Nao'),
	(223, 'D', 'Estrela D’Alva', 'Nao'),
	(224, 'A', 'Indiana', 'Nao'),
	(224, 'B', 'Japonesa', 'Nao'),
	(224, 'C', 'Chinesa', 'Sim'),
	(224, 'D', 'Coreana', 'Nao'),
	(225, 'A', 'Zooterapia', 'Nao'),
	(225, 'B', 'Zoogeografia', 'Sim'),
	(225, 'C', 'Zodíaco', 'Nao'),
	(225, 'D', 'Zoometria', 'Nao'),
	(226, 'A', 'Física', 'Sim'),
	(226, 'B', 'Biologia', 'Nao'),
	(226, 'C', 'Química', 'Nao'),
	(226, 'D', 'Botânica', 'Nao'),
	(227, 'A', 'Uma República', 'Nao'),
	(227, 'B', 'Uma Monarquia Constitucional', 'Sim'),
	(227, 'C', 'Um Emirado', 'Nao'),
	(227, 'D', 'Um Principado', 'Nao'),
	(228, 'A', 'Garganta', 'Nao'),
	(228, 'B', 'Intestino', 'Sim'),
	(228, 'C', 'Pulmões', 'Nao'),
	(228, 'D', 'Rins', 'Nao'),
	(229, 'A', 'Átila', 'Nao'),
	(229, 'B', 'Minotauro', 'Nao'),
	(229, 'C', 'Perseu', 'Nao'),
	(229, 'D', 'Hércules', 'Sim'),
	(230, 'A', 'Zigoto', 'Sim'),
	(230, 'B', 'Bigoto', 'Nao'),
	(230, 'C', 'Feto', 'Nao'),
	(230, 'D', 'Garoto', 'Nao'),
	(231, 'A', 'Estados Unidos', 'Nao'),
	(231, 'B', 'Dinamarca', 'Nao'),
	(231, 'C', 'Canadá', 'Sim'),
	(231, 'D', 'França', 'Nao'),
	(232, 'A', 'Holanda', 'Nao'),
	(232, 'B', 'Rússia', 'Sim'),
	(232, 'C', 'Espanha', 'Nao'),
	(232, 'D', 'África do Sul', 'Nao'),
	(233, 'A', 'Goiás', 'Sim'),
	(233, 'B', 'Mato Grosso', 'Nao'),
	(233, 'C', 'Pará', 'Nao'),
	(233, 'D', 'Maranhão', 'Nao'),
	(234, 'A', 'Tobias Barreto', 'Nao'),
	(234, 'B', 'Dorival Caimi', 'Nao'),
	(234, 'C', 'Machado de Assis', 'Nao'),
	(234, 'D', 'Castro Alves', 'Sim'),
	(235, 'A', 'Alagado', 'Nao'),
	(235, 'B', 'Manguezal', 'Nao'),
	(235, 'C', 'Pântano', 'Nao'),
	(235, 'D', 'Estuário', 'Sim'),
	(236, 'A', 'Uva', 'Nao'),
	(236, 'B', 'Café', 'Sim'),
	(236, 'C', 'Melão', 'Nao'),
	(236, 'D', 'Laranja', 'Nao'),
	(237, 'A', '1987', 'Nao'),
	(237, 'B', '1990', 'Nao'),
	(237, 'C', '1985', 'Nao'),
	(237, 'D', '1888', 'Sim'),
	(238, 'A', 'Mônaco', 'Nao'),
	(238, 'B', 'San Marino', 'Sim'),
	(238, 'C', 'Nova Zelândia', 'Nao'),
	(238, 'D', 'China', 'Nao'),
	(239, 'A', 'Sol', 'Sim'),
	(239, 'B', 'Lua', 'Nao'),
	(239, 'C', 'Estrela', 'Nao'),
	(239, 'D', 'Foice e Martelo', 'Nao'),
	(240, 'A', 'Platão', 'Nao'),
	(240, 'B', 'Júlio Verne', 'Nao'),
	(240, 'C', 'Aristóteles', 'Nao'),
	(240, 'D', 'René Descartes', 'Sim'),
	(241, 'A', 'Cyrus Mccormick', 'Nao'),
	(241, 'B', 'Thomas Edison', 'Nao'),
	(241, 'C', 'Michelangelo', 'Nao'),
	(241, 'D', 'Galileu Galilei', 'Sim'),
	(242, 'A', 'Braço', 'Sim'),
	(242, 'B', 'Perna', 'Nao'),
	(242, 'C', 'Quadril', 'Nao'),
	(242, 'D', 'Coluna', 'Nao'),
	(243, 'A', 'Luiz XIV', 'Sim'),
	(243, 'B', 'Luiz XV', 'Nao'),
	(243, 'C', 'Luiz XVI', 'Nao'),
	(243, 'D', 'Napoleão Bonaparte', 'Nao'),
	(244, 'A', 'Arthur Antunes Coimbra', 'Sim'),
	(244, 'B', 'Arthur Alves Pinto', 'Nao'),
	(244, 'C', 'Arthur da Távola', 'Nao'),
	(244, 'D', 'Arthur dos Santos', 'Nao'),
	(245, 'A', 'Renegar', 'Nao'),
	(245, 'B', 'Sujeitar', 'Nao'),
	(245, 'C', 'Desmaiar', 'Nao'),
	(245, 'D', 'Pedir', 'Sim'),
	(246, 'A', 'La Paz', 'Nao'),
	(246, 'B', 'Buenos Aires', 'Nao'),
	(246, 'C', 'Bogotá', 'Nao'),
	(246, 'D', 'Cuzco', 'Sim'),
	(247, 'A', 'Cabo Jefferson', 'Nao'),
	(247, 'B', 'Cabo Uncoln', 'Nao'),
	(247, 'C', 'Cabo Kennedy', 'Sim'),
	(247, 'D', 'Cabo Reagan', 'Nao'),
	(248, 'A', 'Dentro De', 'Nao'),
	(248, 'B', 'Debaixo De', 'Nao'),
	(248, 'C', 'Fora De', 'Sim'),
	(248, 'D', 'Atrás De', 'Nao'),
	(249, 'A', 'Los Angeles', 'Nao'),
	(249, 'B', 'Chicago', 'Nao'),
	(249, 'C', 'Hope', 'Sim'),
	(249, 'D', 'Dallas', 'Nao'),
	(250, 'A', 'Mármore', 'Sim'),
	(250, 'B', 'Granito', 'Nao'),
	(250, 'C', 'Gesso', 'Nao'),
	(250, 'D', 'Quartizo', 'Nao'),
	(251, 'A', 'Capricórnio', 'Nao'),
	(251, 'B', 'Virgem', 'Nao'),
	(251, 'C', 'Câncer', 'Sim'),
	(251, 'D', 'Leão', 'Nao'),
	(252, 'A', 'Pitágoras', 'Nao'),
	(252, 'B', 'Diderot', 'Nao'),
	(252, 'C', 'Aristóteles', 'Sim'),
	(252, 'D', 'Galileu Galilei', 'Nao'),
	(253, 'A', 'Monet', 'Nao'),
	(253, 'B', 'Rendir', 'Nao'),
	(253, 'C', 'Picasso', 'Sim'),
	(253, 'D', 'Leonardo Da Vinci', 'Nao'),
	(254, 'A', '1921', 'Nao'),
	(254, 'B', '1931', 'Sim'),
	(254, 'C', '1941', 'Nao'),
	(254, 'D', '1951', 'Nao'),
	(255, 'A', 'Budista', 'Nao'),
	(255, 'B', 'Islâmica', 'Sim'),
	(255, 'C', 'Católica', 'Nao'),
	(255, 'D', 'Protestante', 'Nao'),
	(256, 'A', 'Milão', 'Nao'),
	(256, 'B', 'Florença', 'Sim'),
	(256, 'C', 'Veneza', 'Nao'),
	(256, 'D', 'Gênova', 'Nao'),
	(257, 'A', 'Itália', 'Nao'),
	(257, 'B', 'França', 'Nao'),
	(257, 'C', 'Grécia', 'Sim'),
	(257, 'D', 'Turquia', 'Nao'),
	(258, 'A', 'F', 'Nao'),
	(258, 'B', 'H', 'Nao'),
	(258, 'C', 'J', 'Nao'),
	(258, 'D', 'T', 'Sim'),
	(259, 'A', 'Primeira Guerra Mundial', 'Nao'),
	(259, 'B', 'Guerra Do Vietnã', 'Nao'),
	(259, 'C', 'Guerra Da Coréia', 'Nao'),
	(259, 'D', 'Segunda Guerra Mundial', 'Sim'),
	(260, 'A', 'Avalanche de Neve', 'Nao'),
	(260, 'B', 'Fungo', 'Nao'),
	(260, 'C', 'Inclinação de Terreno', 'Sim'),
	(260, 'D', 'Rito Islâmico', 'Nao'),
	(261, 'A', 'Baixo', 'Nao'),
	(261, 'B', 'Perfeito', 'Sim'),
	(261, 'C', 'Atrevido', 'Nao'),
	(261, 'D', 'Enfermo', 'Nao'),
	(262, 'A', 'Mário Quintana', 'Nao'),
	(262, 'B', 'Manuel Bandeira', 'Nao'),
	(262, 'C', 'Vinícius de Morais', 'Nao'),
	(262, 'D', 'Carlos Drummond de Andrade', 'Sim'),
	(263, 'A', 'Santa-Fé', 'Nao'),
	(263, 'B', 'Loco-Breque', 'Nao'),
	(263, 'C', 'American', 'Nao'),
	(263, 'D', 'Baronesa', 'Sim'),
	(264, 'A', 'Barriga da Perna', 'Nao'),
	(264, 'B', 'Menina dos Olhos', 'Nao'),
	(264, 'C', 'Língua', 'Nao'),
	(264, 'D', 'Céu da Boca', 'Sim'),
	(265, 'A', 'Casas', 'Nao'),
	(265, 'B', 'Violinos', 'Sim'),
	(265, 'C', 'Armas', 'Nao'),
	(265, 'D', 'Estradas', 'Nao'),
	(266, 'A', 'Mike Powel', 'Nao'),
	(266, 'B', 'Ben Johnson', 'Sim'),
	(266, 'C', 'Carl Lewis', 'Nao'),
	(266, 'D', 'Linford Christie', 'Nao'),
	(267, 'A', 'Xerografia', 'Nao'),
	(267, 'B', 'Ultra-Sonografia', 'Sim'),
	(267, 'C', 'Fotografia', 'Nao'),
	(267, 'D', 'Radiografia', 'Nao'),
	(268, 'A', 'Baleagem', 'Nao'),
	(268, 'B', 'Balística', 'Sim'),
	(268, 'C', 'Logística', 'Nao'),
	(268, 'D', 'Impressão Digital', 'Nao'),
	(269, 'A', 'Ferro', 'Nao'),
	(269, 'B', 'Aço', 'Nao'),
	(269, 'C', 'Mercúrio', 'Sim'),
	(269, 'D', 'Ouro', 'Nao'),
	(270, 'A', 'Corrimão', 'Nao'),
	(270, 'B', 'Carrilhão', 'Sim'),
	(270, 'C', 'Badalada', 'Nao'),
	(270, 'D', 'Corselete', 'Nao'),
	(271, 'A', '3,05 Metros', 'Sim'),
	(271, 'B', '2,97 Metros', 'Nao'),
	(271, 'C', '3,10 Metros', 'Nao'),
	(271, 'D', '3,00 Metros', 'Nao'),
	(272, 'A', 'Feiticeira', 'Nao'),
	(272, 'B', 'Raposa', 'Nao'),
	(272, 'C', 'Bruxa', 'Nao'),
	(272, 'D', 'Macaca', 'Sim'),
	(273, 'A', 'Jorge Amado', 'Nao'),
	(273, 'B', 'Eça de Queiroz', 'Nao'),
	(273, 'C', 'Rui Barbosa', 'Sim'),
	(273, 'D', 'Raimundo Corrêa', 'Nao'),
	(274, 'A', 'Espinoza', 'Nao'),
	(274, 'B', 'Miguel de Cervantes', 'Sim'),
	(274, 'C', 'Carlos Conte', 'Nao'),
	(274, 'D', 'Angel Morita', 'Nao'),
	(275, 'A', 'Holandesa', 'Nao'),
	(275, 'B', 'Inglesa', 'Sim'),
	(275, 'C', 'Francesa', 'Nao'),
	(275, 'D', 'Brasileira', 'Nao'),
	(276, 'A', 'Afranio Antônio Costa', 'Nao'),
	(276, 'B', 'Guilherme Paraense', 'Sim'),
	(276, 'C', 'Fernando Soledade', 'Nao'),
	(276, 'D', 'Sebastião Wolf', 'Nao'),
	(277, 'A', 'Júpiter', 'Nao'),
	(277, 'B', 'Vênus', 'Nao'),
	(277, 'C', 'Terra', 'Nao'),
	(277, 'D', 'Marte', 'Sim'),
	(278, 'A', 'Renoir', 'Nao'),
	(278, 'B', 'Gauguin', 'Sim'),
	(278, 'C', 'Cézanne', 'Nao'),
	(278, 'D', 'Monet', 'Nao'),
	(279, 'A', 'Aminoácido', 'Nao'),
	(279, 'B', 'Hidrato de Carbono', 'Sim'),
	(279, 'C', 'Lipídio', 'Nao'),
	(279, 'D', 'Proteína', 'Nao'),
	(280, 'A', 'Espanha', 'Sim'),
	(280, 'B', 'Suécia', 'Nao'),
	(280, 'C', 'Hungria', 'Nao'),
	(280, 'D', 'França', 'Nao'),
	(281, 'A', 'Janis Joplin', 'Nao'),
	(281, 'B', 'Carole King', 'Nao'),
	(281, 'C', 'Aretha Franklin', 'Sim'),
	(281, 'D', 'Diana Ross', 'Nao'),
	(282, 'A', 'Micronésia', 'Nao'),
	(282, 'B', 'Melanésia', 'Sim'),
	(282, 'C', 'Polinésia', 'Nao'),
	(282, 'D', 'Indonésia', 'Nao'),
	(283, 'A', 'Egito', 'Nao'),
	(283, 'B', 'Canadá', 'Nao'),
	(283, 'C', 'Líbano', 'Sim'),
	(283, 'D', 'Marrocos', 'Nao'),
	(284, 'A', 'A cidade Perdida de Ouro', 'Nao'),
	(284, 'B', 'A fonte da Juventude', 'Sim'),
	(284, 'C', 'Unicórnios', 'Nao'),
	(284, 'D', 'Seu Gato', 'Nao'),
	(285, 'A', 'Stanley', 'Nao'),
	(285, 'B', 'Wedells', 'Nao'),
	(285, 'C', 'Medanosa', 'Nao'),
	(285, 'D', 'Falkland', 'Sim'),
	(286, 'A', 'Quênia', 'Nao'),
	(286, 'B', 'Equador', 'Nao'),
	(286, 'C', 'Chile', 'Sim'),
	(286, 'D', 'Indonésia', 'Nao'),
	(287, 'A', 'Espanha', 'Nao'),
	(287, 'B', 'Holanda', 'Nao'),
	(287, 'C', 'França', 'Sim'),
	(287, 'D', 'Itália', 'Nao'),
	(288, 'A', 'Dinamarca', 'Sim'),
	(288, 'B', 'Inglaterra', 'Nao'),
	(288, 'C', 'Noruega', 'Nao'),
	(288, 'D', 'Estados Unidos', 'Nao'),
	(289, 'A', 'Cubismo', 'Sim'),
	(289, 'B', 'Surrealismo', 'Nao'),
	(289, 'C', 'Impressionismo', 'Nao'),
	(289, 'D', 'Realismo', 'Nao'),
	(290, 'A', 'Espeleólogo', 'Sim'),
	(290, 'B', 'Agrostólogo', 'Nao'),
	(290, 'C', 'Psicólogo', 'Nao'),
	(290, 'D', 'Campaólogo', 'Nao'),
	(291, 'A', 'Ferroviário', 'Nao'),
	(291, 'B', 'Aéreo', 'Nao'),
	(291, 'C', 'Hidroviário', 'Nao'),
	(291, 'D', 'Rodoviário', 'Sim'),
	(292, 'A', 'Cetáceos', 'Sim'),
	(292, 'B', 'Felinos', 'Nao'),
	(292, 'C', 'Sirênios', 'Nao'),
	(292, 'D', 'Carnívaros', 'Nao'),
	(293, 'A', 'Grã-Bretanha', 'Sim'),
	(293, 'B', 'Irlanda', 'Nao'),
	(293, 'C', 'Islândia', 'Nao'),
	(293, 'D', 'Sicília', 'Nao'),
	(294, 'A', 'Judy Gerland', 'Nao'),
	(294, 'B', 'Shirley Temple', 'Nao'),
	(294, 'C', 'Julie Andrews', 'Sim'),
	(294, 'D', 'Doris Day', 'Nao'),
	(295, 'A', 'Getúlio Vargas', 'Nao'),
	(295, 'B', 'Prudente de Moraes', 'Sim'),
	(295, 'C', 'Washington Luís', 'Nao'),
	(295, 'D', 'Tancredo Neves', 'Nao'),
	(296, 'A', 'Os Jardins de Giverny', 'Sim'),
	(296, 'B', 'Os Bistrôs de Paris', 'Nao'),
	(296, 'C', 'Cenas de Moulin Rouge', 'Nao'),
	(296, 'D', 'Paisagens da Provença', 'Nao'),
	(297, 'A', 'Italianos', 'Nao'),
	(297, 'B', 'Portugueses', 'Nao'),
	(297, 'C', 'Espanhóis', 'Sim'),
	(297, 'D', 'Chilenos', 'Nao'),
	(298, 'A', 'Jacques Stewart', 'Nao'),
	(298, 'B', 'Alain Prost', 'Nao'),
	(298, 'C', 'Ayrton Senna', 'Nao'),
	(298, 'D', 'J.Manoel Fangio', 'Sim'),
	(299, 'A', 'Enforcados', 'Nao'),
	(299, 'B', 'Fuzilados', 'Nao'),
	(299, 'C', 'Guilhotinados', 'Sim'),
	(299, 'D', 'Queimados', 'Nao'),
	(300, 'A', 'Materografia', 'Nao'),
	(300, 'B', 'Litografia', 'Nao'),
	(300, 'C', 'Xilografia', 'Sim'),
	(300, 'D', 'Serigrafia', 'Nao');
/*!40000 ALTER TABLE `alternativas` ENABLE KEYS */;

-- Copiando estrutura para tabela showdomilhao.perguntas
CREATE TABLE IF NOT EXISTS `perguntas` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Nome` varchar(200) DEFAULT NULL,
  `Nivel` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=301 DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela showdomilhao.perguntas: ~227 rows (aproximadamente)
/*!40000 ALTER TABLE `perguntas` DISABLE KEYS */;
INSERT INTO `perguntas` (`ID`, `Nome`, `Nivel`) VALUES
	(1, 'Em que estado brasileiro nasceu a apresentadora Xuxa?', 1),
	(2, 'Qual é o nome dado ao estado da água em forma de gelo?', 1),
	(3, 'Qual era o apelido da cantora Elis Regina?', 1),
	(4, 'Quem é a namorada do Mickey?', 1),
	(5, 'Qual é o personagem do folclore brasileiro que tem uma perna só?', 1),
	(6, 'Fidel Castro nasceu em que país?', 1),
	(7, 'Quem proclamou a república no Brasil em 1889?', 1),
	(8, 'Quem é o patrono do exército brasileiro?', 1),
	(9, 'Quem era o apresentador que reprovava os calouros tocando uma buzina?', 1),
	(10, 'O que era Frankenstein, de Mary Shelley?', 1),
	(11, 'Qual é o signo do zodíaco de quem nasce no dia do ano-novo?', 1),
	(12, 'Quem fundou a fábrica de automóveis Ford?', 1),
	(13, 'Qual é a cor que se associa com os grupos ecológicos?', 1),
	(14, 'A água ferve a quantos graus centígrados?', 1),
	(15, 'Quando é comemorado o dia da independência do Brasil?', 1),
	(16, 'Qual lugar é também chamado de Santa Sé?', 1),
	(17, 'Quem tem por lema a frase: "Sempre alerta"?', 1),
	(18, 'Quem foi o grande amor de Julieta?', 1),
	(19, 'Quantos signos formam o zodíaco?', 1),
	(20, 'Vatapé é uma comida típica de qual estado?', 1),
	(21, 'Como se chama o lugar onde são armazenadas as balas de revólver?', 1),
	(22, 'Qual personagem da turma da Mônica tem apenas cinco fios de cabelo?', 1),
	(23, 'Qual cantora tinha o apelido de "Ternurinha" na época da jovem guarda?', 1),
	(24, 'O churrasco é considerado uma comida típica de qual estado?', 1),
	(25, 'Qual cantor é o pai da dupla Sandy e Júnior?', 1),
	(26, 'Quem foi o criador dos personagens Pedrinho,Narizinho e Emília?', 1),
	(27, 'Quem fundou a Microsoft?', 1),
	(28, 'Qual é o nome dado ao pneu reserva do carro?', 1),
	(29, 'Qual é o nome do cachorro medroso do Salsicha, dos desenhos animados?', 1),
	(30, 'Quantas dentições naturais tem o ser humano durante a vida?', 1),
	(31, 'Edinho, filho de Pelé, jogou no Santos em que posição?', 1),
	(32, 'Qual é a pedra preciosa mais dura encontrada na natureza?', 1),
	(33, 'Como se chama o lugar onde se guardam vinhos?', 1),
	(34, 'Qual cantor ficou conhecido como "o rei do rock"?', 1),
	(35, 'Quem é o inimigo de Piu-Piu nos desenhos aimados?', 1),
	(36, 'Joana Prado é o nome verdadeiro de qual artista?', 1),
	(37, 'Quantos dias tem um ano bissexto?', 1),
	(38, 'Qual é o réptil que muda de cor conforme o lugar em que está?', 1),
	(39, 'Qual é a duração de cada tempo de uma partida de futebol?', 1),
	(40, 'Onde fica o centro da indústria cinematográfica nos EUA?', 1),
	(41, 'Qual era o código da identidade secreta de James Bond?', 1),
	(42, 'Qual é a fruta associada com a cidade de Laranjal?', 1),
	(43, 'Quantos centavos equivalem a um real?', 1),
	(44, 'De acordo com a Bíblia, qual era o "fruto proibido"?', 1),
	(45, 'Como é conhecida a ponte que liga Rio de Janeiro a Niterói?', 1),
	(46, 'Em que ano os portugueses descobriram o Brasil?', 1),
	(47, 'O que é medido por um termômetro?', 1),
	(48, 'O rio Amazonas pertence a qual continente?', 1),
	(49, 'Quem esculpiu o boneco Pinóquio, no conto de Carlo Lorenzini?', 1),
	(50, 'Qual é a moeda oficial dos Estados Unidos?', 1),
	(51, 'Qual foi o placar no final da Copa de 98, quando o Brasil perdeu para a França?', 1),
	(52, 'Quantas folhas tem um trevo de sorte?', 1),
	(53, 'Qual é a cidade conhecida como "terra da garoa"?', 1),
	(54, 'Qual ator do cinema brasileiro é conhecido por ter uhas enormes?', 1),
	(55, 'O violoncelo é um tipo de instrumento de?', 1),
	(56, 'Com que fruta a Branca de Neve foi envenenada?', 1),
	(57, 'Quem foi técnico da Seleção brasileira de futebol na Copa de 98?/', 1),
	(58, 'Em que cidade é realizada a corrida de São Silvestre?', 1),
	(59, 'Qual é a área da medicina que trata de crianças?', 1),
	(60, 'O sâque é uma bebida típica de qual país?', 1),
	(61, 'O dromedário tem quantas corcovas?', 1),
	(62, 'Um adulto sadio tem quantos dentes na boca?', 1),
	(63, 'Qual dos sete anões usa óculos?', 1),
	(64, 'Quem é o Homem de Aço das histórias em quadrinhos?', 1),
	(65, 'Cavalo, rainha e torre são peças de qual jogo?', 1),
	(66, 'Turmalina é uma espécie de quê?', 1),
	(67, 'Qual é o santo casamenteiro?', 1),
	(68, 'Quem ocupou o cargo de Ministro da Saúde do Brasil no ano de 2000?', 1),
	(69, 'Segundo a Bíblia, quem foi morto por Caim?', 1),
	(70, 'Qual é o livro dividido em Velho Testamento e Novo Testamento?', 1),
	(71, 'Qual objeto é usado como arma pelo Pinguim do Batman?', 1),
	(72, 'Qual ser mitológico possui o corpo metade mulher metade peixe?', 1),
	(73, 'Qual foi o nome dado ao movimento liderado por Tiradentes?', 1),
	(74, 'Qual é o país de origem do vinho champanha?', 1),
	(75, 'Qual destes elementos se forma dentro das ostras?', 1),
	(76, 'Quando é comemorado o dia da mentira no Brasil?', 1),
	(77, 'Em que estado nasceu a cantora Elba Ramalho?', 1),
	(78, 'Quando é comemorado o dia da criança?', 1),
	(79, 'De qual lugar o personagem Tarzan era considerado rei?', 1),
	(80, 'Quem é a mulher do Tarzan?', 1),
	(81, 'Qual é o animal que puxa o trenó do Papai Noel?', 1),
	(82, 'Capixaba é quem nasce em qual estado brasileiro?', 1),
	(83, 'Quantos titulares possui uma equipe de vôlei', 1),
	(84, 'Qual é o profissional que conduz o elevador?', 1),
	(85, 'Segundo a Bíbla, quantos apóstolos tinha Jesus Cristo?', 1),
	(86, 'Em qual país surgiu a Máfia?', 1),
	(87, 'Qual é o profissional que usa o estetoscópio?', 1),
	(88, 'Fernando Henrique Cardoso é formado em que área?', 1),
	(89, 'Qual destes é considerado o mês das noivas?', 1),
	(90, 'Quem inventou o telefone?', 1),
	(91, 'Qual é o esporte praticado com pequenos aviões de controle remoto?', 1),
	(92, 'Qual é o significado da frase inglesa "I love you"?', 1),
	(93, 'Qual personagem lidera o bando da floresta de Sherwood?', 1),
	(94, 'Qual é a cor da pedra rubi?', 1),
	(95, 'Qual é a planta que fortalece o marinheiro Popeye?', 1),
	(96, 'Quando é comemorado o dia de Santo Antônio?', 1),
	(97, 'Qual era a profissão exercida por Lula, antes de ele ser presidente do PT?', 1),
	(98, 'Quem foi o amor do imperador Marco Antônio?', 1),
	(99, 'Qual estação do ano fica entre o verão e o inverno?', 1),
	(100, 'Como Joana d`Arc foi morta?', 1),
	(101, 'Quantos jogadores um jogo de vôlei reúne na quadra?', 2),
	(102, 'Qual é o país do tango?', 2),
	(103, 'Que imperador pôs fogo em Roma?', 2),
	(104, 'A cidade de Pompéia, que foi soterrada por um vulcão fica em qual desses países?', 2),
	(105, 'Como é chamado quem nasce em Milão, na Itália?', 2),
	(106, 'Que profissional usa uma ferramenta chamada formão?', 2),
	(107, 'Em qual estádio pelé marcou seu milésimo gol?', 2),
	(108, 'O que é um oboé?', 2),
	(109, 'Como era chamado os pilotos suícidas da Segunda Guerra?', 2),
	(110, 'O que é gôndola?', 2),
	(111, 'Sashimi é um prato originário de qual país?', 2),
	(112, 'Como é chamada a cantora que representa o papel principal em uma ópera?', 2),
	(113, 'Peroba é uma espécie de?', 2),
	(114, 'O alpinismo é praticado em que lugar?', 2),
	(115, 'O coliseu é um monumento histórico de que cidade européia?', 2),
	(116, 'Qual é o ponto mais alto da Terra?', 2),
	(117, 'Que rio corta a cidade de Londres, na inglaterra?', 2),
	(118, 'Qual é a raça do personagem principal do filme "Beethoven"?', 2),
	(119, 'Quem foi eleito presidente da África do Sul em 1994?', 2),
	(120, 'Qual cantor ficou cohecido como "O rei da voz"?', 2),
	(121, 'Quantos quilates tem o ouro puro?', 2),
	(122, 'Qual é a sigla da organização das Nações Unidas?', 2),
	(123, 'De quantos em quantos anos aparece o cometa Halley?', 2),
	(124, 'Segundo a crença popular, a mula sem cabeça é mulher de quem? ', 2),
	(125, 'Que atiz protagonizou o filme "titanic"?', 2),
	(126, 'Como é chamada a doença que causa perda desigual da melanina?', 2),
	(127, 'Que realizou a primeira cirurgia de ponte de safena no Brasil?', 2),
	(128, 'No filme, quem era parceiro de crimes da Bonnie?', 2),
	(129, 'Qual é a moeda oficial da Alemanha?', 2),
	(130, 'Quem foi o assassino de Lee Harvey Oswald?', 2),
	(131, 'Quem é o parceiro de aventuras de Dom Quixote?', 2),
	(132, 'Nas histórias do Snoopy, qual é o nome do passarinho?', 2),
	(133, 'Que metal avermelhado cria uma camada esverdeada em contato com a umidade?', 2),
	(134, 'Que planta era usada para fabricação de papel no antigo Egito?', 2),
	(135, 'Que país europeu tem como atração a tourada?', 2),
	(136, 'Que humorista, falecido em 1999, foi baterista de Raul Seixas?', 2),
	(137, 'O que os filatelistas colecionam?', 2),
	(138, 'Quem pintou o quadro "La Gioconda", conhecido como "Mona Lisa"?', 2),
	(139, 'Em que cidade está situada a famosa Praça Vermelha?', 2),
	(140, 'Qual é o nome do vulcão que sepultou cidades na Itália no ano de 79?', 2),
	(141, 'Quando começou e terminou a Primeira Guerra Mundial?', 2),
	(142, 'Qual é a letra do alfabeto que simboliza o número dez em algarismo romano?', 2),
	(143, 'Qual é a história que Francis Ford Coppola dirigiu em três partes?', 2),
	(144, 'Que animais são criados nas pocilgas?', 2),
	(145, 'Quem foi o diretor do filme "A lista de Schindler"?', 2),
	(146, 'Qual é o alimento produzido pela moagem dos grãos de cacau?', 2),
	(147, 'Quem introduziu o futebol no Brasil?', 2),
	(148, 'Em que continente se situa o rio Nilo?', 2),
	(149, 'Que colônia britânica foi devolvida à China em 1997? ', 2),
	(150, 'Nova Delhi é a capital de que país?', 2),
	(151, 'O que leva o sangue do coração para o corpo?', 2),
	(152, 'Como é chamado o objeto falsificado vendido como original?', 2),
	(153, 'Em que matéria estuda-se álgebra na escola?', 2),
	(154, 'Qual é o nome original do filme "O médico e o monstro"?', 2),
	(155, 'Que atriz casou com Joe Dimaggio e Arthur Miller?', 2),
	(156, 'Quem disse a frase: “Vim, vi e venci”?', 2),
	(157, 'Que nome se dá à volta dos cardumes de peixes para a nascente do rio?', 2),
	(158, 'Qual é o país que participou de todas as copas do mundo de futebol, até 1998?', 2),
	(159, 'Quais são os naipes vermelhos do baralho?', 2),
	(160, 'Qual é o nome verdadeiro do Batman?', 2),
	(161, 'Beirute é a capital de que país?', 2),
	(162, 'O que é um contratorpedeiro?', 2),
	(163, 'Às margens de que riacho foi proclamada a Independência do Brasil?', 2),
	(164, 'O “super bowl” faz parte de qual esporte?', 2),
	(165, 'Qual é o nome da embarcação típica do litoral nordestino brasileiro?', 2),
	(166, 'Em que estado norte-americano fica a cidade de Miami?', 2),
	(167, 'Qual é a capital do Iraque?', 2),
	(168, 'Como se chama a máquina usada para compactar o asfalto?', 2),
	(169, 'Em 1991, que esportista americano se afastou do basquete por ser HIV positivo?', 2),
	(170, 'Qual é o nome do cachorro de Charlie Brown?', 2),
	(171, 'Qual presidente dos Estados Unidos foi ator de cinema?', 2),
	(172, 'Como é chamado o templo sagrado dos judeus?', 2),
	(173, 'A que categoria pertence o cavalo-marinho?', 2),
	(174, 'O FBI é a polícia federal de qual país?', 2),
	(175, 'Em que cidade brasileira fica o Instituto Tecnológico de Aeronáutica?', 2),
	(176, 'Em que cidade foram realizados os jogos olímpicos de 2000?', 2),
	(177, 'Em que país fica a grande muralha com cerca de 6.400 quilômetros?', 2),
	(178, 'Qual é o nome do Patriarca da Independência do Brasil?', 2),
	(179, 'O nome América foi associado a qual desses nomes?', 2),
	(180, 'Qual é o médico que mais utiliza o eletrocardiograma?', 2),
	(181, 'Qual o significado da sigla “AI”, no AI-5?', 2),
	(182, 'Qual personagem bíblico dividiu as águas do Mar Vermelho?', 2),
	(183, 'Qual dessas cobras não é venenosa?', 2),
	(184, 'Que animal é usado no jogo de pólo?', 2),
	(185, 'Em que ano ocorreu o incêndio do edifício Joelma, na cidade de São Paulo?', 2),
	(186, 'Teresina é a capital de qual estado brasileiro?', 2),
	(187, 'Sobre qual cidade do Japão foi lançada a primeira bomba atômica?', 2),
	(188, 'O daltônico é deficiente em?', 2),
	(189, 'Qual é o dia da Padroeira do Brasil?', 2),
	(190, 'Qual é a capital do Estado de Mato Grosso do Sul?', 2),
	(191, 'Quantos são os continentes?', 2),
	(192, 'Por que nome são conhecidas as pessoas do Pólo Ártico?', 2),
	(193, 'Qual é a fórmula química da água?', 2),
	(194, 'Qual era a profissão de Cecília Meirelles?', 2),
	(195, 'Em que cidade fica a sede da rede de TV BBC?', 2),
	(196, 'Camillo é o sobrenome de qual cantor nascido em Brotas?', 2),
	(197, 'Por quantos integrantes era formado o grupo Beatles?', 2),
	(198, 'Qual foi o último imperador do Brasil?', 2),
	(199, 'Quem dirigiu o filme “Central do Brasil”?', 2),
	(200, 'O que significa a expressão e-mail?', 2),
	(201, 'Em qual espécie o macho choca os ovos e a fêmea procura alimento?', 3),
	(202, 'Em qual país está localizado o “Muro das lamentações”?', 3),
	(203, 'Qual desses países não fica na Ásia?', 3),
	(204, 'Qual desses astros de filmes de ação é belga?', 3),
	(205, 'Onde foi conduzida a vitória das forças aliadas na Segunda Guerra Mundial?', 3),
	(206, 'Onde nasceu Van Gogh, o grande pintor impressionista?', 3),
	(207, 'Qual é a primeira letra do alfabeto grego?', 3),
	(208, 'Qual presidente brasileiro instituiu o AI-5?', 3),
	(209, 'O que significa literalmente Perestroika?', 3),
	(210, 'Qual desses quatro pesos é o mais leve?', 3),
	(211, 'Brahma é o deus de que religião?', 3),
	(212, 'Os nazistas foram julgados em:', 3),
	(213, 'Que ramo da pecuária ocupa-se de bodes e cabras?', 3),
	(214, 'Qual oceano tem o maior volume de água?', 3),
	(215, 'Qual foi o último presidente militar do Brasil?', 3),
	(216, 'Que conflito ideológico envolveu os EUA e a União Soviética?', 3),
	(217, 'O trapézio é um músculo que está situado:', 3),
	(218, 'Quem escreveu o livro “A sangue frio” em 1966?', 3),
	(219, 'Quem escreveu “Ulisses” em 1922?', 3),
	(220, 'Qual o símbolo químico do radônio?', 3),
	(221, 'O que são meninges?', 3),
	(222, 'Qual produto gerou guerras e conflitos no século XX?', 3),
	(223, 'Como é chamada a bola de gelo e poeira que orbita em torno do sol?', 3),
	(224, 'O confucionismo é uma filosofia de qual nacionalidade?', 3),
	(225, 'Qual a ciência que estuda a distribuição dos animais?', 3),
	(226, 'A eletrônica é parte de qual ciência?', 3),
	(227, 'A Bélgica é:', 3),
	(228, 'Que parte do corpo humano é infectada pela cólera?', 3),
	(229, 'Que figura mitológica é conhecida por sua força extraordinária?', 3),
	(230, 'A união do espermatozóide com o óvulo origina uma célula chamada:', 3),
	(231, 'A que país pertence a ilha de Terra Nova?', 3),
	(232, 'Em que país você pode gastar rublos?', 3),
	(233, 'Na criação do Estado do Tocantins, que estado teve o território reduzido?', 3),
	(234, 'De quem é este verso: “A praça é do povo, como o céu é do condor”?', 3),
	(235, 'Que nome recebe a foz de um rio que se abre para o mar?', 3),
	(236, '“Arábica” e “robusta” são tipos de quê?', 3),
	(237, 'Em que ano Ayrton Senna venceu o primeiro campeonato de Fórmula 1?', 3),
	(238, 'Qual é a menor República do mundo?', 3),
	(239, 'Que símbolo está desenhado no centro da bandeira Argentina?', 3),
	(240, 'De quem é a frase ”Penso, logo existo”?', 3),
	(241, 'Quem construiu o primeiro telescópio astronômico completo?', 3),
	(242, 'Em que parte do nosso corpo está o úmero?', 3),
	(243, 'A quem se atribui a frase “Eu sou o Estado”?', 3),
	(244, 'Qual o nome verdadeiro do jogador de futebol conhecido com Zico?', 3),
	(245, 'O que significa deprecar?', 3),
	(246, 'Que cidade foi capital do Império Inca?', 3),
	(247, 'Com que outro nome é conhecido o Cabo Canaveral?', 3),
	(248, 'Que significa o prefixo exo?', 3),
	(249, 'Bill Clinton nasceu em que cidade?', 3),
	(250, 'Qual foi o material utilizado na construção do Partenon de Atenas?', 3),
	(251, 'Que trópico atravessa o Saara?', 3),
	(252, 'Quem foi aluno de Platão e tutor de Alexandre, o Grande?', 3),
	(253, '“Guernica” é uma tela de qual pintor?', 3),
	(254, 'Em que ano foi inaugurada a estátua do Cristo Redentor no Rio de Janeiro?', 3),
	(255, 'Qual é a religião majoritária da Turquia?', 3),
	(256, 'Onde estão os sepulcros de Michelangelo, Maquiavel e Galileu?', 3),
	(257, 'A que país deve-se viajar para subir o Monte Parnaso?', 3),
	(258, 'A que letra do nosso alfabeto corresponde a letra grega tau?', 3),
	(259, 'Em qual guerra lutou Paul Newman pela marinha americana?', 3),
	(260, 'O que é talude?', 3),
	(261, 'Qual destas palavras é sinônimo de cabal?', 3),
	(262, 'Qual desses poetas foi indicado para o prêmio Nobel de literatura?', 3),
	(263, 'Qual foi a locomotiva a vapor que trafegou na Estrada de Ferro Mauá em 1854?', 3),
	(264, 'O que é palato?', 3),
	(265, 'O que construía Stradivarius?', 3),
	(266, 'Qual atleta foi desclassificado por uso de doping nas Olimpíadas de 1988?', 3),
	(267, 'Qual é o exame que emite ondas sonoras para visualizar os órgãos?', 3),
	(268, 'Qual é a especialidade dos profissionais que analisam os sulcos e marcas de uma bala?', 3),
	(269, 'Qual metal possui o símbolo Hg?', 3),
	(270, 'Qual é o nome dado a um conjunto de sinos?', 3),
	(271, 'Qual é a altura oficial do aro na cesta no basquete?', 3),
	(272, 'Qual é o apelido do time da Ponte Preta?', 3),
	(273, 'Quem foi chamado de Águia de Haia?', 3),
	(274, 'Quem escreveu “Dom Quixote”?', 3),
	(275, 'Qual a origem da palavra folclore?', 3),
	(276, 'Quem ganhou a 1ª medalha de ouro olímpico para o Brasil?', 3),
	(277, 'Qual é o quarto planeta do sistema solar?', 3),
	(278, 'Que pintor francês consagrou a mulher taitiana em suas telas?', 3),
	(279, 'O que é glicose?', 3),
	(280, 'Qual destas seleções nunca jogou uma final de copa?', 3),
	(281, 'Qual foi a primeira mulher a entrar no “hall da fama” do rock and roll?', 3),
	(282, 'Nova Caledônia faz parte da:', 3),
	(283, 'Qual é o país que tem uma árvore estampada na bandeira?', 3),
	(284, 'O que procurava Juan Ponce de Leon quando descobriu a Flórida?', 3),
	(285, 'As Ilhas Malvinas também são chamadas de:', 3),
	(286, 'Qual destes países não se situa no Equador?', 3),
	(287, 'Em que país Leonardo da Vinci viveu seus últimos dias?', 3),
	(288, 'A que país pertence a Groenlândia?', 3),
	(289, 'Pablo Picasso foi um dos criadores do:', 3),
	(290, 'Como se chama o explorador de grutas e cavernas?', 3),
	(291, 'Qual o sistema de transporte mais utilizado no Brasil?', 3),
	(292, 'A baleia está classificada em qual grupo de mamíferos?', 3),
	(293, 'Qual é a maior ilha da Europa?', 3),
	(294, 'O filme “A noviça rebelde”, premiado com 5 Oscars, foi estrelado por:', 3),
	(295, 'Qual foi o primeiro presidente do Brasil eleito pelo povo?', 3),
	(296, 'O que o pintor Claude Monet representou em suas telas?', 3),
	(297, 'Miró, Picasso e Salvador Dalí eram pintores:', 3),
	(298, 'Qual foi o piloto de Fórmula 1 que conquistou o título de campeão mundial cinco vezes?', 3),
	(299, 'Como o rei francês Luis XVI e sua esposa Maria Antonieta morreram?', 3),
	(300, 'Como é chamada a gravura impressa sobre pranchas de madeira?', 3);
/*!40000 ALTER TABLE `perguntas` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
